/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'createdAt' : Time,
  'slug' : string,
  'tags' : Array<string>,
  'author' : string,
  'coverImage' : [] | [string],
  'updatedAt' : Time,
  'excerpt' : string,
}
export interface ContactForm {
  'name' : string,
  'submittedAt' : Time,
  'email' : string,
  'message' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<[BlogPost], bigint>,
  'deleteBlogPost' : ActorMethod<[bigint], boolean>,
  'filterBlogPosts' : ActorMethod<
    [Array<string>, [] | [boolean]],
    Array<BlogPost>
  >,
  'getAllContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getBlogPostById' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getBlogPostBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getBlogPosts' : ActorMethod<[bigint, bigint], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchContactForms' : ActorMethod<[string], Array<ContactForm>>,
  'submitContactForm' : ActorMethod<[ContactForm], boolean>,
  'updateBlogPost' : ActorMethod<[BlogPost], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];